#camel.springboot.main-run-controller=true
camel.main.name=camel-spring
management.endpoints.web.base-path=/observe
management.enabled=true
management.server.port=9876
management.health.probes.enabled=true
management.jolokiaEnabled = true
