apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: camel-spring-jolokia
    camel.apache.org/app: camel-spring-jolokia
    app.kubernetes.io/runtime: camel
    camel/integration-runtime: camel
    app.openshift.io/runtime: camel
  name: camel-spring-jolokia
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: jolokia
    port: 8778
    protocol: TCP
    targetPort: jolokia
  selector:
    app.kubernetes.io/name: camel-spring-jolokia
  type: ClusterIP
