apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    camel.apache.org/observability-services-port: "8080"
  labels:
    app.kubernetes.io/name: camel-spring
    app.kubernetes.io/runtime: camel
    app.openshift.io/runtime: camel
    camel/integration-runtime: camel
    camel.apache.org/app: camel-spring
  name: camel-spring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: camel-spring
  template:
    metadata:
      labels:
        app.kubernetes.io/name: camel-spring
    spec:
      containers:
      - name: camel-spring
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
