apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: camel-spring
    camel.apache.org/app: camel-spring
    app.kubernetes.io/runtime: camel
    camel/integration-runtime: camel
    app.openshift.io/runtime: camel
    app.kubernetes.io/component: management
  name: camel-spring-management
spec:
  ports:
  - name: management
    port: 9876
    protocol: TCP
    targetPort: 9876
  selector:
    app.kubernetes.io/name: camel-spring
  type: ClusterIP
