apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: camel-main
    camel.apache.org/app: camel-main
    app.kubernetes.io/runtime: camel
    camel/integration-runtime: camel
    app.openshift.io/runtime: camel
  name: camel-main
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: camel-main
  type: ClusterIP
