apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: camel-main-metrics
  labels:
    app: camel-main
    openshift.io/user-monitoring: "true"
spec:
  selector:
    matchLabels:
      app: camel-main
  endpoints:
  - port: management
    path: /observe/metrics
    scheme: http
    interval: 30s