camel.main.name=camel-main
camel.main.basePackageScan=org.demo.camel
camel.server.enabled=true
camel.management.enabled=true
camel.management.health-check-enabled=true
camel.management.port=9876
camel.management.metricsEnabled=true
camel.metrics.enabled=true
camel.metrics.binders=processor,jvm-info,jvm-memory,file-descriptor