apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: camel-quarkus
    camel.apache.org/app: camel-quarkus
    app.kubernetes.io/runtime: camel
    camel/integration-runtime: camel
    app.openshift.io/runtime: camel
  name: camel-quarkus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: camel-quarkus
  template:
    metadata:
      labels:
        app.kubernetes.io/name: camel-quarkus
    spec:
      containers:
      - image: camel-quarkus:1.0-SNAPSHOT
        name: camel-quarkus
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
