apiVersion: v1
kind: Service
metadata:
  annotations:
    camel/camel-core-version: 4.11.0-SNAPSHOT
  labels:
    app.kubernetes.io/name: camel-quarkus
    camel/integration-runtime: camel
    app.kubernetes.io/runtime: camel
  name: camel-quarkus
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: camel-quarkus
  type: ClusterIP
